# tasks file for haproxy
---
- name: install | add repository from PPA and install its signing key
  apt_repository:
    repo: "{{ haproxy_ppa }}"
    update_cache: true
  tags:
    - haproxy-install-add-repository

- name: install | dependencies
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ haproxy_dependencies }}"
  tags:
    - haproxy-install-dependencies

- name: install | additional
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ haproxy_install }}"
  tags:
    - haproxy-install-additional
