# tasks file
---
- name: acl | create directories
  ansible.builtin.file:
    path: "{{ acl_file.dest | dirname }}"
    state: directory
    owner: "{{ acl_file.owner | default('root') }}"
    group: "{{ acl_file.group | default('root') }}"
    mode: '0750'
  loop: "{{ haproxy_acl_files }}"
  loop_control:
    loop_var: acl_file
  tags:
    - haproxy-acl-create-directories

- name: acl | update files
  ansible.builtin.template:
    src: etc/haproxy/acl.j2
    dest: "{{ acl_file.dest }}"
    owner: "{{ acl_file.owner | default('root') }}"
    group: "{{ acl_file.group | default('root') }}"
    mode: "{{ acl_file.mode | default('0640') }}"
  loop: "{{ haproxy_acl_files }}"
  loop_control:
    loop_var: acl_file
  notify: restart haproxy
  tags:
    - haproxy-acl-update-files
