# tasks file
---
- name: certificates | create directories
  ansible.builtin.file:
    path: "{{ ssl_map.dest | dirname }}"
    state: directory
    owner: "{{ ssl_map.owner | default('root') }}"
    group: "{{ ssl_map.group | default('root') }}"
    mode: '0750'
  loop: "{{ haproxy_ssl_map }}"
  loop_control:
    loop_var: ssl_map
  when: ssl_map.state is undefined or ssl_map.state == 'present'
  tags:
    - haproxy-certificates-create-directories

- name: certificates | copy files
  ansible.builtin.copy:
    src: "{{ ssl_map.src }}"
    dest: "{{ ssl_map.dest }}"
    owner: "{{ ssl_map.owner | default('root') }}"
    group: "{{ ssl_map.group | default('root') }}"
    mode: "{{ ssl_map.mode | default('0640') }}"
  loop: "{{ haproxy_ssl_map }}"
  loop_control:
    loop_var: ssl_map
  when: ssl_map.state is undefined or ssl_map.state == 'present'
  notify: restart haproxy
  tags:
    - haproxy-certificates-copy-files

- name: certificates | remove files
  ansible.builtin.file:
    path: "{{ ssl_map.dest }}"
    state: absent
  loop: "{{ haproxy_ssl_map }}"
  loop_control:
    loop_var: ssl_map
  when: ssl_map.state is defined and ssl_map.state == 'absent'
  notify: restart haproxy
  tags:
    - haproxy-certificates-remove-files
