# tasks file
---
- name: install | dependencies
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ haproxy_dependencies }}"
  tags:
    - haproxy-install-dependencies

- name: install | additional
  ansible.builtin.apt:
    name: "{{ haproxy_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - haproxy-install-additional
