# tasks file for haproxy
---
- name: scripts | copy SSL deploy script
  template:
    src: "{{ haproxy_scripts_ssl_deploy_template }}"
    dest: "{{ haproxy_scripts_ssl_deploy }}"
    owner: root
    group: root
    mode: 0755
  tags:
    - haproxy-scripts-ssl-deploy

- name: scripts | copy OCSP deploy script
  template:
    src: "{{ haproxy_scripts_ocsp_deploy_template }}"
    dest: "{{ haproxy_scripts_ocsp_deploy }}"
    owner: root
    group: root
    mode: 0755
  tags:
    - haproxy-scripts-ocsp-deploy

- name: scripts | configure (cron) job for OCSP deploy
  cron:
    name: haproxy-ocsp-deploy
    job: "{{ haproxy_scripts_ocsp_deploy }}"
    state: "{{ haproxy_scripts_ocsp_deploy_job.state | default('absent') }}"
    day: "{{ haproxy_scripts_ocsp_deploy_job.day | default('*') }}"
    hour: "{{ haproxy_scripts_ocsp_deploy_job.hour | default(0) }}"
    minute: "{{ haproxy_scripts_ocsp_deploy_job.minute | default('*') }}"
    month: "{{ haproxy_scripts_ocsp_deploy_job.month | default('*') }}"
    weekday: "{{ haproxy_scripts_ocsp_deploy_job.weekday | default('*') }}"
    cron_file: haproxy-ocsp-deploy
    user: root
  tags:
    - haproxy-scripts-cron-ocsp-deploy
