# handlers file for haproxy
---
- name: restart haproxy
  service:
    name: haproxy
    state: restarted

- name: reload systemd
  command: systemctl daemon-reload
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"
